### ISSUE TITLE
dohover will display backslash-escape for the special characters

### ISSUE THREAD

**Issue by kevinhwang91** [josa42/coc-go#97] opened 2020-08-20 08:50 UTC
issue image:
![image](https://user-images.githubusercontent.com/17562139/90748401-bb4d4880-e304-11ea-9e88-5e4168907b6e.png)

**Comment by josa42** [comment] 2020-08-25 11:37
I don't think this is caused by `coc-go`. Looking at the trace, it seems to me that this is an issue with `gopls` or potentially `coc.nvim`:

```
[Trace - 1:33:01 PM] Received response 'textDocument/hover - (31)' in 2ms.
Result: {
    "contents": {
        "kind": "markdown",
        "value": "```go\nfunc sort.Sort(data sort.Interface)\n```\n\n[`sort.Sort` on pkg.go.dev](https://pkg.go.dev/sort#Sort)\n\nSort sorts data\\.\nIt makes one call to data\\.Len to determine n, and O\\(n\\*log\\(n\\)\\) calls to\ndata\\.Less and data\\.Swap\\. The sort is not guaranteed to be stable\\.\n"
    },
    "range": {
        "start": {
            "line": 5,
            "character": 6
        },
        "end": {
            "line": 5,
            "character": 10
        }
    }
}
```

**Comment by kevinhwang91** [comment] 2020-08-25 16:51
Could coc-go intercept the result and rewrite it properly? vscode-go without this issue.

**Comment by flw-cn** [comment] 2020-09-11 16:19
Is there any workaround here? I've encountered more than that, and some `&nbsp` that have caused alignment problems.

**Comment by flw-cn** [comment] 2020-09-13 08:48
I used Wireshark to capture the packets and confirmed that the results returned by gopls are in the correct format.

What else might cause additional backslash?

```
Content-Length: 349

{"jsonrpc":"2.0","result":{"contents":{"kind":"plaintext","value":"func sort.Sort(data sort.Interface)\nSort sorts data.\nIt makes one call to data.Len to determine n, and O(n*log(n)) calls to\ndata.Less and data.Swap. The sort is not guaranteed to be stable.\n"},"range":{"start":{"line":82,"character":6},"end":{"line":82,"character":10}}},"id":3}
```

**Comment by chemzqm** [comment] 2020-09-13 10:14
https://github.com/neoclide/coc.nvim/issues/2308

**Comment by flw-cn** [comment] 2020-09-13 17:43
@kevinhwang91 You can try `Plug “flw-cn/vim-markdown”` which is a fork for `plasticboy/vim-markdown` and it automatically hides the backslash. see PR plasticboy/vim-markdown#515 to see exactly what it does.

**Comment by josa42** [comment] 2020-09-29 19:13
Closing this because it needs to be fixed in coc.nvim

**Closed by josa42** 2020-09-29 19:13 UTC
Labels: bug

**Comment by anhtumai** [comment] 2023-03-12 13:53
@kevinhwang91 @josa42 How can you config coc-go to open hover window? When I doHover, it opens new panel with horizon split like this:
![image](https://user-images.githubusercontent.com/32799668/224549133-7c74dc16-4780-4361-9ac8-70f0ae85d02c.png)
