### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by AgentCosmic** [josa42/coc-go#75] opened 2020-04-20 03:47 UTC
I can't install this plugin. Here's the error message:

```
[coc.nvim] Failed to install 'gopls'
[coc.nvim] Error: exited with 1
[coc.nvim] Failed to install 'gomodifytags'
[coc.nvim] Failed to install 'gotests'
```

**Comment by josa42** [comment] 2020-05-19 07:54
Please, add more information on how to reproduce the issue.

**Comment by AgentCosmic** [comment] 2020-05-19 08:55
I run `:CocInstall coc-go`, and once coc tells me the installation is successful, I close vim and open a .go file. The error message immediately comes up without me needing to do anything. I have other coc-extensions installed. I also have vim-go plugin which uses gopls. I'm on Windows 10, vim 8.2, go 1.14.
Thanks.

**Comment by qige96** [comment] 2020-06-20 11:15
discussion in [issue #6](https://github.com/josa42/coc-go/issues/6)  might help.

**Comment by josa42** [comment] 2020-07-01 19:01
Duplicate of #6

**Closed by josa42** 2020-07-01 19:01 UTC
Labels: Windows, bug, help wanted
