### ISSUE TITLE
Why not install gopls when running :CocInstall coc-go?

### ISSUE THREAD

**Issue by michaelperel** [josa42/coc-go#158] opened 2021-09-13 21:50 UTC
Thanks so much for making this extension :)

For my workflow, I develop in a container. This means that in my Dockerfile, I install coc.nvim and extensions for the languages that I use.

However, with coc-go, I noticed that gopls is not installed when I execute :CocInstall coc-go in the Dockerfile. Instead, gopls gets installed by coc-go asynchronously once when I start editing a file. With docker, you commonly start or rebuild new containers. This means that many times when I run a container, I need to wait for coc-go to install gopls.

Would it be possible for :CocInstall coc-go to also install gopls? Why would installing the extension not install gopls?

To satisfy my usecase, I [install gopls in my container manually](https://github.com/michaelperel/dev-container/blob/7c8f54ec95569540dc77383a1d9e24d1ee6c43d7/.devcontainer/Dockerfile#L133) and unfortunately do not use coc-go. With other language extensions, this seems not to be the case, which [leads to an easier install experience](https://github.com/michaelperel/dev-container/blob/7c8f54ec95569540dc77383a1d9e24d1ee6c43d7/.devcontainer/Dockerfile#L122).

**Comment by luisdavim** [comment] 2021-09-30 20:30
You can run `:CocCommand go.install.tools` so you could for example use something like `vi -E -c 'CocCommand go.install.tools' -c qall`

**Comment by josa42** [comment] 2021-11-03 19:15
Sorry I won't fix this, as it works as intended. You can point `go.goplsPath` to you gopls binary if don't want coc-go to install gopls.

**Closed by josa42** 2021-11-03 19:15 UTC
