### ISSUE TITLE
Does not install on Windows

### ISSUE THREAD

**Issue by dakyskye** [josa42/coc-go#87] opened 2020-06-30 21:27 UTC
```
[coc.nvim] Error: exited with 1
Error: Command failed: set GOBIN=C:\Users\dakyskye\AppData\Local\coc\extensions\coc-go-data\bin & set GOPATH=C:\Users\dakyskye\AppData\Local\coc\extensions\coc-go-data\tools & set GO111MODULE=on & go get golang.org/x/tools/gopls@latest
go: unknown environment setting GO111MODULE=on
go: unknown environment setting GO111MODULE=on
```

**Comment by josa42** [comment] 2020-07-01 19:01
Duplicate of #6

**Closed by josa42** 2020-07-01 19:01 UTC

**Comment by dakyskye** [comment] 2020-07-02 13:50
Not a duplicant, he gets `'GOPATH' is not recognized as an internal or external comman` :) By the way I think I know why is this. `set` works for `cmd`, but not for PowerShell.
